services:
    _defaults:
        public: false

    Runroom\RenderEventBundle\Renderer\PageRenderer:
        arguments:
            $twig: '@twig'
            $eventDispatcher: '@event_dispatcher'
            $pageViewModel: '@runroom.render_event.page_view_model'

    runroom.render_event.page_view_model: ~
